# typed: false
# frozen_string_literal: true

# Generated by the protected Crabbox release tooling. DO NOT EDIT.
class Crabbox < Formula
  desc "Remote software testing and execution"
  homepage "https://github.com/openclaw/crabbox"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/crabbox/releases/download/v0.46.0/crabbox_0.46.0_darwin_amd64.tar.gz"
      sha256 "18035770b5b654114fa95d2e468268b13c69862137cc1f083bd674bbb2bf83bb"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/crabbox/releases/download/v0.46.0/crabbox_0.46.0_darwin_arm64.tar.gz"
      sha256 "2216da0acbcc6e822ee341ec313aaab58875db951fa1daf0d13dd710ebfba9b8"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.46.0/crabbox_0.46.0_linux_amd64.tar.gz"
      sha256 "6a9341e810307356361dbed4c4b84be28a036b5cc291af1566d2ccd376570d90"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v0.46.0/crabbox_0.46.0_linux_arm64.tar.gz"
      sha256 "d95730856cd3909dab0703ec024e3017a094fff2a065516782b47019fec9533d"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  test do
    system bin/"crabbox", "--version"
  end
end
