# typed: false
# frozen_string_literal: true

# Generated by the protected Crabbox release tooling. DO NOT EDIT.
class Crabbox < Formula
  desc "Remote software testing and execution"
  homepage "https://github.com/openclaw/crabbox"
  version "0.42.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openclaw/crabbox/releases/download/v#{version}/crabbox_#{version}_darwin_amd64.tar.gz"
      sha256 "d04f053ee5f1f38a189397ffe55ba4f048d6030412fdbc695ca268af6c315809"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openclaw/crabbox/releases/download/v#{version}/crabbox_#{version}_darwin_arm64.tar.gz"
      sha256 "e812e9fc5ecb55eb9a809488f261b5d2e810bdea1ae546c611416f69bb99dfe1"

      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v#{version}/crabbox_#{version}_linux_amd64.tar.gz"
      sha256 "7f0b0925439e1d4b7e71ee083e1d259e2b68096f43e25b25bd815d4c385fe4a0"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openclaw/crabbox/releases/download/v#{version}/crabbox_#{version}_linux_arm64.tar.gz"
      sha256 "d8f219abc3afb947ca392a4c594148302c096d22262c7a78afee6a5f196bf276"
      define_method(:install) do
        bin.install "crabbox"
        bin.install "crabbox-apple-vm-helper" if OS.mac? && Hardware::CPU.arm?
      end
    end
  end

  test do
    system bin/"crabbox", "--version"
  end
end
